### PR TITLE
Fix for missing keys in device json answer

### PR DESCRIPTION
**Pull request by chemelli74**
Some devices, like Fritz 7590 with firmware 7.27, may have empty data[] answer.

Proposed change will fix this and make the library working also for those devices.

### CODE REVIEW

**Comment by eifinger** [comment]
Have you tested that change?

It seems like this won't work

Short test:

```python
import requests

r = requests.get('https://api.github.com/events')

r.json()[0]
```

```text
{'id': '16669300949',
 'type': 'PushEvent',
 'actor': {'id': 61843437,
  'login': 'enricemcorro',
  'display_login': 'enricemcorro',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/enricemcorro',
  'avatar_url': 'https://avatars.githubusercontent.com/u/61843437?'},
 'repo': {'id': 245396736,
  'name': 'enricemcorro/enricemcorro',
  'url': 'https://api.github.com/repos/enricemcorro/enricemcorro'},
 'payload': {'push_id': 7273662154,
  'size': 1,
  'distinct_size': 1,
  'ref': 'refs/heads/master',
  'head': '668af1e21268b5c07594072f951af10f67968853',
  'before': '6267cd3d6e2ce14c7fbf3cdba7895dc76a3e8254',
  'commits': [{'sha': '668af1e21268b5c07594072f951af10f67968853',
    'author': {'email': 'enricemcorro@gmail.com', 'name': 'enricemcorro'},
    'message': 'penis^2',
    'distinct': True,
    'url': 'https://api.github.com/repos/enricemcorro/enricemcorro/commits/668af1e21268b5c07594072f951af10f67968853'}]},
 'public': True,
 'created_at': '2021-06-07T08:52:40Z'}
```

```python
"push_id" in r.json()[0]
```

`False`

**Comment by chemelli74** [comment]
> Have you tested that change?

Yup and works fine here.
The issue is that in the json there is a empty data[] so you cannot search for "active".

> ```python
> "push_id" in r.json()[0]
> ```

Try with
```python
value = r.json()[0]["not_exist"]
```

vs

```python
if "not_exist" on r.json()[0]:
  value = r.json()[0]["not_exist"]
```

**Comment by eifinger** [comment]
What do you mean by empty data?
Can you give an example how that looks?

Your change currently checks if `active` is in `json`. Shouldn't it rather check if `data` is in `json`?

**Comment by chemelli74** [comment]
> What do you mean by empty data?
> Can you give an example how that looks?

`json` is `{'pid': 'netDev', 'hide': {'shareUsb': True, 'faxSet': True, 'dectRdio': True, 'dslSpec': True, 'ssoSet': True, 'liveImg': True, 'dslStat': True, 'dslSet': True, 'liveTv': True, 'dectMoni': True, 'provServ': True, 'dectMoniEx': True, 'rss': True, 'mobile': True, 'dslFeed': True, 'dslOv': True, 'dslGraph': True, 'dectMail': True}, 'time': [], 'data': [], 'sid': 'db56b43d77755111'}`
 
> Your change currently checks if `active` is in `json`. Shouldn't it rather check if `data` is in `json`?

`data` is there, `active` not ;-)

Please check with my PR, works fine here and profiles are finally successfully retrieved.

Simone

**Comment by eifinger** [comment]
Your PR might work for you but it will break functionality for others.

Please check again with your code. You have to check if `active` is in `json["data"]` not if it is in `json`

**Comment by chemelli74** [comment]
> Your PR might work for you but it will break functionality for others.

I don't see how.

> Please check again with your code. You have to check if `active` is in `json["data"]` not if it is in `json`

Done

**Comment by eifinger** [comment]
> > Your PR might work for you but it will break functionality for others.
> 
> I don't see how.

Devices would have never been populated with your old change

**Comment by svb007** [comment]
Not sure why checks  are failing on my PR, but I managed to fix the missing data in the FB 7490 by adding "xhrId": "all" to the post data. See my 3rd commit here: https://github.com/eifinger/fritz-switch-profiles/pull/5

**Pull request merged**
